/*
 * Copyright 2024 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */
#include <openssl/asn1.h>
#include <openssl/asn1t.h>
#include <openssl/x509.h>
#include "x509_local.h"
#include <stdio.h>
#include <openssl/x509v3.h>
#include <openssl/ts.h>

ASN1_SEQUENCE(PCV2_TRAIT) = {
    ASN1_SIMPLE(PCV2_TRAIT, traitId, ASN1_OBJECT),
    ASN1_SIMPLE(PCV2_TRAIT, traitCategory, ASN1_OBJECT),
    ASN1_SIMPLE(PCV2_TRAIT, traitRegistry, ASN1_OBJECT),
    ASN1_IMP_OPT(PCV2_TRAIT, description, ASN1_UTF8STRING, 0),
    ASN1_IMP_OPT(PCV2_TRAIT, descriptionURI, ASN1_UTF8STRING, 1),
    ASN1_SIMPLE(PCV2_TRAIT, traitValue, ASN1_OCTET_STRING)
} ASN1_SEQUENCE_END(PCV2_TRAIT)

IMPLEMENT_ASN1_FUNCTIONS(PCV2_TRAIT)

ASN1_SEQUENCE(HASHED_CERTIFICATE_IDENTIFIER) = {
    ASN1_SIMPLE(HASHED_CERTIFICATE_IDENTIFIER, hashValue, X509_ALGOR),
    ASN1_SIMPLE(HASHED_CERTIFICATE_IDENTIFIER, hashOverSignatureValue, ASN1_OCTET_STRING)
} ASN1_SEQUENCE_END(HASHED_CERTIFICATE_IDENTIFIER)

IMPLEMENT_ASN1_FUNCTIONS(HASHED_CERTIFICATE_IDENTIFIER)

ASN1_SEQUENCE(PCV2_CERTIFICATE_IDENTIFIER) = {
    ASN1_IMP_OPT(PCV2_CERTIFICATE_IDENTIFIER, hashedCertIdentifier, HASHED_CERTIFICATE_IDENTIFIER, 0),
    ASN1_IMP_OPT(PCV2_CERTIFICATE_IDENTIFIER, genericCertIdentifier, OSSL_ISSUER_SERIAL, 1)
} ASN1_SEQUENCE_END(PCV2_CERTIFICATE_IDENTIFIER)

IMPLEMENT_ASN1_FUNCTIONS(PCV2_CERTIFICATE_IDENTIFIER)

ASN1_SEQUENCE(COMMON_CRITERIA_EVALUATION) = {
    ASN1_SIMPLE(COMMON_CRITERIA_EVALUATION, cCMeasures, COMMON_CRITERIA_MEASURES),
    ASN1_SIMPLE(COMMON_CRITERIA_EVALUATION, cCCertificateNumber, ASN1_UTF8STRING),
    ASN1_SIMPLE(COMMON_CRITERIA_EVALUATION, cCCertificateAuthority, ASN1_UTF8STRING),
    ASN1_IMP_OPT(COMMON_CRITERIA_EVALUATION, evaluationScheme, ASN1_UTF8STRING, 0),
    ASN1_IMP_OPT(COMMON_CRITERIA_EVALUATION, cCCertificateIssuanceDate, ASN1_GENERALIZEDTIME, 1),
    ASN1_IMP_OPT(COMMON_CRITERIA_EVALUATION, cCCertificateExpiryDate, ASN1_GENERALIZEDTIME, 2)
} ASN1_SEQUENCE_END(COMMON_CRITERIA_EVALUATION)

IMPLEMENT_ASN1_FUNCTIONS(COMMON_CRITERIA_EVALUATION)

ASN1_SEQUENCE(ISO9000_CERTIFICATION) = {
    ASN1_OPT(ISO9000_CERTIFICATION, iso9000Certified, ASN1_FBOOLEAN),
    ASN1_SIMPLE(ISO9000_CERTIFICATION, iso9000Uri, ASN1_IA5STRING),
} ASN1_SEQUENCE_END(ISO9000_CERTIFICATION)

IMPLEMENT_ASN1_FUNCTIONS(ISO9000_CERTIFICATION)
